#!/usr/bin/python
# coding: utf8

import os
from optparse import OptionParser
from colorama import Fore

from core import brute_types, output


# -------------- #

TYPE_LIST_STR = ''
LOGIN_LIST = None
PASSWORD_LIST = None

for i in os.listdir ('scripts'): TYPE_LIST_STR += ('\n' + i.replace('.py', ''))

op = OptionParser ('--one-login <login> --llist <path to login-list file> -d <path to dictionary with passwords> --brute-type <brute-type>')
op.add_option ('--one-login', dest='ologin', type='string', help='if you want to use one login and brute it, than set login at this flag')
op.add_option ('--llist', dest='llist', type='string', help='if you want to use file with logins, than set path to file at this flag')
op.add_option ('--brute-type', dest='btype', type='string', help='select one of avalible brute types: ' + TYPE_LIST_STR)
op.add_option ('-d', '--dictionary', dest='di', type='string', help='set path to file with password at this flag')
op.add_option ('--dd', dest='dd', action='store_true', default=False, help='use this flag if you want to use default password dictionary')
(op, args) = op.parse_args ()

def main ():
    
    banner = '''
    ████───████──█─█──███──████──███
    █──██──█──█──█─█───█───█──█──█
    ████───████──█─█───█───█──█──███
    █──██──█─█───█─█───█───█──█────█
    ████───█─█───███───█───████──███
    '''
    info = '''
    ''' + Fore.CYAN + '''[DEVELOPERS] ''' + Fore.WHITE + '''BLACK HAT LTD.
    ''' + Fore.CYAN + '''[VERSION] ''' + Fore.WHITE + '''0.6
    ''' + Fore.RESET
    print Fore.RED + banner + Fore.RESET
    print info

    brute_types.parse_json_config ('config/config.json')
    
    if op.dd:
        fl = open ('db/dict.lst')
    else:
        fl = open (op.di)


    if op.ologin is not None:
        try:
            brute_types.runmodule (op.btype, op.ologin, fl)
        except KeyboardInterrupt:
            print '\n' + output.INFO + 'Stoped'
    else:
        f = open (op.llist, 'r')
        brute_types.runmodule (op.btype, f.readlines(), fl)
        f.close ()
            
if __name__ == '__main__':
    main ()
